#! /bin/sh
### BEGIN INIT INFO
# Provides:          gbtele
# Should-Start:      console-screen kbd acpid dbus hal consolekit
# Required-Start:    $local_fs $remote_fs x11-common
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Light Display Manager
# Description:       Debian init script for the Light Display Manager
### END INIT INFO
#
# Author:       Yves-Alexis Perez <corsac@debian.org> using gdm script from 
#               Ryan Murray <rmurray@debian.org>
#

# To start lightdm even if it is not the default display manager, change
# HEED_DEFAULT_DISPLAY_MANAGER to "false."
HEED_DEFAULT_DISPLAY_MANAGER=true
DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager

case "$1" in
  start)
	echo 'timing start'
	sudo sh /home/pi/hlrfw/scripts/auto_timing.sh &
  ;;
  stop)
	echo 'timing stop'
	sudo kill $(ps aux | grep -m 1 'sh /home/pi/hlrfw/scripts/auto_timing.sh' | awk '{ print $2 }')
  ;;
  restart|force-reload)
        $0 stop
        sleep 1
        $0 start
  ;;
  status)
        status_of_proc -p "$PIDFILE" "$DAEMON" gbtele && exit 0 || exit $?
  ;;
  *)
        echo "Usage: /etc/init.d/gbtele {start|stop|restart|reload|force-reload|status}"
        exit 1
  ;;
esac

exit 0
